### PR TITLE
Gppk integrated dev

### PR DESCRIPTION
**Pull request by eastabrooka**

### CODE REVIEW

**Comment by eastabrooka** [comment]
image

image

Hey look ! It keeps your history. 

Even has your face on it.

**Comment by gppk** [comment]
I do like my face. But youve moved it into a folder not with the same name as the .ino folder so Arduino is going to get upset.

**Comment by eastabrooka** [comment]
Ono. Will fix.

**Comment by eastabrooka** [comment]
There you go. 
image

**Comment by eastabrooka** [comment]
Id love to say "Works on my machine" but I can't figure out what Package to add to make it work for the Lora - It may be worthwhile noting this in Human-Zombie-Device.ino at the top.

**Review by gppk — COMMENTED** [review]
Doesn't build, but that's my code. Will merge and fix.

**Pull request merged**
